events { }

http {
    server {
        listen 80;

        # Movies
        location /api/movies {
            proxy_pass http://localhost:3001/movies;
        }

        # Reviews
        location /api/reviews {
            proxy_pass http://localhost:3002/reviews;
        }

        # Users
        location /api/users {
            proxy_pass http://localhost:3003/users;
        }
    }
}
